# Generated by Django 5.0.2 on 2024-02-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
